version: "3.7"
services:
  django-corn:
    build: .
    image: django-corn:1.0
    ports:
      - "8000:8000"
    volumes: 
      - .:/app
    env_file: 
      - .env_file
  nginx:
    build: ./nginx_confdir
    image: "nginx_adapted:1.18"
    ports:
      - "80:80"
    volumes: 
      - ./static:/app/static
    depends_on: 
      - django-corn
volumes: 
  .: