version: "3.7"
services:
  mysql:
    image: mysql:5.7.43
    ports:
      - "3306:3306"
    volumes: 
      - ./msql_dev_volume:/var/lib/mysql
    env_file: 
      - .env_file
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p$${MYSQL_ROOT_PASSWORD}"]
      retries: 30
      timeout: 5s

  django-corn:
    image: django-backend:1.1
    ports:
      - "8000:8000"
    # volumes: 
    #   - .:/app
    env_file: 
      - .env_file
    depends_on: 
      mysql:
        condition: service_healthy

  nginx:
    image: "nginx_adapted:1.18"
    ports:
      - "80:80"
    volumes: 
      - ./static:/app/static
    depends_on: 
      - django-corn
